version: "3.3"

services:
  redis:
    image: "redis:6.2"
    environment:
      TZ: Asia/Shanghai
    ports:
      - "6380:6379"
    command: [ "redis-server","/etc/redis.conf" ]
    restart: always
    volumes:
      - ./etc/redis.conf:/etc/redis.conf
      - ./data:/data
