version: '3.3'

services:
    zoo1:
      image: 'zookeeper:3.6.3'
      container_name: zoo1
      hostname: zoo1
      environment:
        ZOO_MY_ID: 1
        ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181
        ALLOW_ANONYMOUS_LOGIN: "yes"
      ports:
        - "2181:2181"
        - "8081:8080"